version: "3.9"

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: tourney
    ports:
      - "5444:5432"

volumes:
  postgres:
